name: CICD Workflow - Build and deploy to ACR

on:
  push:
    branches:
      - cicd

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout your code repository
  
      - name: Setup Node.js
        uses: actions/setup-node@v2  # Set up Node.js environment
        with:
          node-version: '20'  # Adjust Node.js version as needed

      - name: Install dependencies
        run: npm install  # Install Node.js dependencies
  
      - name: Run unit tests
        run: npm test  # Execute unit tests using npm test script


  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.ACR_SERVER }}/backend
      BUILD_PATH: ./
      DOCKERFILE_PATH: ./Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate build ID
        id: tag
        run: |
          echo "BUILD_ID=$(TZ='Asia/Taipei' date +"%Y%m%d_%H%M%S")" >> $GITHUB_ENV
          echo "COMMIT_ID=$(git log -1 --pretty=%h)" >> $GITHUB_ENV

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ env.BUILD_PATH }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.BUILD_ID }}_${{ env.COMMIT_ID }}
          file: ${{ env.DOCKERFILE_PATH }}
      
      - name: Update image tag of Helm chart
        run: |
          sed -i 's/tag: ".*"/tag: "${{ env.BUILD_ID }}_${{ env.COMMIT_ID }}"/g' stadium-chart/values.yaml
      
      - name: Commit and push changes
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "106207411@g.nccu.edu.tw"

          git add -A
          git commit -m "helmcharts deployment updated by ${{ env.COMMIT_ID }}"
          git push origin HEAD:cicd
        
